### ISSUE TITLE
US11 Definir requerimientos funcionales para la app a desarrollar (colocarlos en el Product Backlog del Project), a su vez revisar si han cumplimentado todos los requerimientos previos, realizando mejoras del mismo. También mencionar los Requerimientos no funcionales.

### ISSUE THREAD

**Issue by carlos-linero** [Proyectos-ISPC/proyecto-app-mobile#11]
- [x] #TK00 Definir tareas dentro de la Historia de Usuario.
- [x] #TK01 Agregar requerimientos en el [Documento](https://docs.google.com/document/d/169pGeTpQNVCHKGrPRHP7crKAxTiKN185TBbzmbeVbVE/edit).

**Comment by carlos-linero** [comment]
- [x] #TK00 Definir tareas dentro de la Historia de Usuario.
- [ ] #TK01 Agregar requerimientos en el [Documento](https://docs.google.com/document/d/169pGeTpQNVCHKGrPRHP7crKAxTiKN185TBbzmbeVbVE/edit).

**Comment by GiulianaDeEt** [comment]
Hecho y entregado.
