### ISSUE TITLE
US3 Como diseñador de software, quiero elaborar un diagrama modelo de entidad-relación que muestre la relación entre los datos en la aplicación y que refleje los requisitos del negocio, para asegurar una comprensión clara del flujo de información y garantizar que la base de datos respalde adecuadamente las necesidades.

### ISSUE THREAD

**Issue by carlariossuarez** [Proyectos-ISPC/proyecto-app-mobile#3]
- [x] #TK00 Definir tareas dentro de la Historia de Usuario.
- [x] #TK01 Analizar y plasmar en un gráfico el DER
- [x] #TK02 Subir el DER al repo en dentro de la carpeta "Documentación"
- [ ] #TK03 Realizar cambios y correcciones

**Comment by carlos-linero** [comment]
![Image](https://github.com/Proyectos-ISPC/proyecto-app-mobile/assets/43420022/91c7c576-05a2-4d54-8b37-081f3caba9b5)
