### ISSUE TITLE
US33 Como usuario quiero visualizar header para tener acceso directo al carrito de compras y a la opción de regresar al paso anterior

### ISSUE THREAD

**Issue by carlariossuarez** [Proyectos-ISPC/proyecto-app-mobile#33]
- [x] #TK01 Añadir flecha que permita regresar al paso anterior
- [x] #TK02 Añadir carrito de compras que permita acceder al carrito de compras del usuario

![Image](https://github.com/Proyectos-ISPC/proyecto-app-mobile/assets/91499396/14ec8e6f-e322-4f4b-befc-65b11f5f7601)

**Comment by tefsantana** [comment]
Tareas hechas y probadas. Se espera a la aprobación de un PR externo para poder vincular a dev.
