### ISSUE TITLE
US75 Como administrador de la aplicación, quiero que los usuarios puedan acceder a sus cuentas y ver sus datos personales y el historial de compras realizadas para que tengan la posibilidad de gestionar sus perfiles y llevar un registro de sus pedidos realizados en la app.

### ISSUE THREAD

**Issue by carlariossuarez** [Proyectos-ISPC/proyecto-app-mobile#75]
- [x] #TK1 Crear un endpoint con un servicio para que el frontend pueda llamarlo y se puedan visualizar los datos personales (nombre completo y correo electrónico)
- [x] #TK2 Crear un endpoint con un servicio para que, desde el frontend, se puedan modificar los datos personales y el servicio guarde los nuevos cambios.
- [x] #TK3 Crear un endpoint con un servicio que permita, desde el frontend, llamar y consultar todas las compras realizadas para armar el historial de compras hechas del usuario.

**Comment by tefsantana** [comment]
Tareas 1 y 2 terminadas (sección de datos personales y posibilidad de modificarlos)
