### ISSUE TITLE
US90 Como desarrollador de software quiero utilizar Selenium IDE para automatizar casos de prueba en la página web "https://www.saucedemo.com/"

### ISSUE THREAD

**Issue by carlariossuarez** [Proyectos-ISPC/proyecto-app-mobile#90]
Se deben automatizar los casos de prueba que indica el siguiente material de testing
https://acceso.ispc.edu.ar/pluginfile.php/124891/mod_resource/content/3/Modulo%201%20-%203%20-%20Pr%C3%A1ctica%20primer%20Caso%20de%20Prueba%20Sencillo%20Caja%20Negra%20%20-%20%20Testing%20ISP%20-%20Anah%C3%AD%20Hern%C3%A1ndez.docx.pdf

En la clase del dia 24/10 la profesora explica cómo utilizar Selenium y cómo debe ser el archivo .SIDE

**Comment by tefsantana** [comment]
Se adjunta evidencia de la realización de esta historia de usuario.
https://github.com/Proyectos-ISPC/proyecto-app-mobile/wiki/Testing-%F0%9F%90%9E

![image](https://github.com/Proyectos-ISPC/proyecto-app-mobile/assets/83146564/832cfea2-7cb1-4a76-8d83-a04bd2e01626)
